# Generated by Django 5.2.12 on 2026-03-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('year_published', models.IntegerField(blank=True, null=True)),
                ('min_players', models.PositiveIntegerField(null=True)),
                ('max_players', models.PositiveIntegerField(null=True)),
                ('playing_time', models.PositiveIntegerField(null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
